### ISSUE TITLE
Possible bad object file on Win64

### ISSUE THREAD

**Issue by mivade** [conda-forge/cppzmq-feedstock#4]
Trying to link against libzmq.lib (found in `<conda env dir>/Library/bin`), I get an error like so:

```
libzmq.lib: fatal error LNK1106: invalid file or disk full: cannot seek to 0xAD8 [<path to project>.vcxproj]
```

Inspecting libzmq.lib, it is only 471 bytes. The macOS equivalent libzmq.a is 1.2M.

**Comment by JohanMabille** [comment]
That's weird, the library names on windows should be `libzmq-mt-4_2_1.lib` and `libzmq-mt-s-4_2_1.lib`. Do you see these files in your conda install ?

**Comment by mivade** [comment]
Hmm. Those exist in `<conda env dir>/Library/lib`. CMake seems to want to use `libzmq.lib`, though.

**Comment by SylvainCorlay** [comment]
Is this the cmake from a third-party project that tries to use `libzmq.lib`? The recipe installs a `cppzmqConfig.cmake` file which is so that

`find_package(cppzmq  REQUIRED)` would work and point to the right files.

**Comment by mivade** [comment]
That seems to do the trick! Thanks for the quick replies.
